parameters:
  storage_directory: "%kernel.project_dir%/var/storage"
  public_directory: "%kernel.project_dir%/public"

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

    bind:
      $storageDir: "%storage_directory%"
      $env: '%kernel.environment%'

  Meniam\Bundle\CoreBundle\Service\:
    resource: '../../Service/**/*.php'
    exclude:
      - '../../Service/{AbstractService.php}'
    public: true

  Meniam\Bundle\CoreBundle\Twig\Extension\:
    resource: '../../Twig/Extension/**/*.php'
    tags: { name: twig.extension }
    public: true

#  Meniam\Bundle\CoreBundle\Twig\Extension\DateExtension:
#    class: Meniam\Bundle\CoreBundle\Twig\Extension\DateExtension
#    tags: { name: twig.extension }
