parameters:
  storage_directory: "%kernel.project_dir%/var/storage"
  public_directory: "%kernel.project_dir%/public"

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

    bind:
      $storageDir: "%storage_directory%"
      $env: '%kernel.environment%'

  Meniam\Bundle\CoreBundle\Service\:
    resource: '../../Service/**/*.php'
    exclude:
      - '../../Service/{Abstract}Service.php'
    public: true

  Meniam\Bundle\CoreBundle\Twig\Extension\DateExtension:
    class: Meniam\Bundle\CoreBundle\Twig\Extension\DateExtension
    arguments: [ "%date_replaces%" ]
    tags:
      - { name: twig.extension }

  Meniam\Bundle\CoreBundle\Twig\Extension\UrlExtension:
    class: Meniam\Bundle\CoreBundle\Twig\Extension\UrlExtension
    arguments: [ '@Meniam\Bundle\CoreBundle\Service\RequestService' ]
    tags:
      - { name: twig.extension }

  Meniam\Bundle\CoreBundle\Twig\Extension\StupidExtension:
    class: Meniam\Bundle\CoreBundle\Twig\Extension\StupidExtension
    tags:
      - { name: twig.extension }

  Meniam\Bundle\CoreBundle\Twig\Extension\Form\BootstrapExtension:
    class: Meniam\Bundle\CoreBundle\Twig\Extension\Form\BootstrapExtension
    tags:
      - { name: twig.extension }

  Meniam\Bundle\CoreBundle\Twig\Extension\Form\IconExtension:
    class: Meniam\Bundle\CoreBundle\Twig\Extension\Form\IconExtension
    tags:
      - { name: twig.extension }

  Meniam\Bundle\CoreBundle\Twig\Extension\PageMetaExtension:
    class:     Meniam\Bundle\CoreBundle\Twig\Extension\PageMetaExtension
    arguments: [ '@Meniam\Bundle\CoreBundle\Service\PageMeta']
    tags:
      - { name: twig.extension }
    public: true

  Meniam\Bundle\CoreBundle\Twig\TypeExtension\TabExtension:
    class: Meniam\Bundle\CoreBundle\Twig\TypeExtension\TabExtension
    tags:
      - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

    Meniam\Bundle\CoreBundle\Form\Bootstrap\Extension\ButtonTypeExtension:
      tags:
        - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\ButtonType }

    Meniam\Bundle\CoreBundle\Form\Bootstrap\Extension\InputGroupButtonExtension:
      tags:
        - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\TextType }

    Meniam\Bundle\CoreBundle\Form\Bootstrap\Extension\PlaintextControlExtension:
      tags:
        - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }

