parameters:
  storage_directory: "%kernel.project_dir%/var/storage"
  public_directory: "%kernel.project_dir%/public"

  date_replace:
    ru:
      January: Января
      February: Февраля
      March: Марта
      April: Апреля
      May: Мая
      June: Июня
      July: Июля
      August: Августа
      September: Сентября
      October: Остября
      November: Ноября
      December: Декабря
      Jan: Янв
      Feb: Фев
      Mar: Мар
      Apr: Апр
      Jun: Июн
      Jul: Июл
      Aug: Авг
      Sep: Сен
      Oct: Ост
      Nov: Ноя
      Dec: Дек
      Monday: Понедельник
      Tuesday: Вторник
      Wednesday: Среда
      Thursday: Четверт
      Friday: Пятница
      Saturday: Суббота
      Sunday: Воскресенье
      Mon: Пон
      Tue: Вто
      Wed: Сре
      Thu: Чет
      Fri: Пят
      Sat: Суб
      Sun: Вос

services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

    bind:
      $storageDir: "%storage_directory%"
      $env: '%kernel.environment%'

  Meniam\Bundle\CoreBundle\Service\:
    resource: '../../Service/**/*.php'
    exclude:
      - '../../Service/{AbstractService.php}'
    public: true

  Meniam\Bundle\CoreBundle\Twig\Extension\:
    resource: '../../Twig/Extension/**/*.php'
    exclude: '../../Twig/Extension/**/Abstract*.php'
    tags:
      - { name: twig.extension }
    public: true

#  Meniam\Bundle\CoreBundle\Twig\Extension\DateExtension:
#    class: Meniam\Bundle\CoreBundle\Twig\Extension\DateExtension
#    tags: { name: twig.extension }
