services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  Meniam\Bundle\CoreBundle\Service\:
    resource: '../../Service/**/*.php'
    exclude:
      - '../../Service/{AbstractService.php}'
    public: true
