services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

    bind:
      $logger: '@logger'
      $pager: '@Meniam\Bundle\CoreBundle\Service\Pager'
      $storageDir: "%storage_directory%"
      $env: '%kernel.environment%'

  Meniam\Bundle\CoreBundle\Service\:
    resource: '../../Service/**/*.php'
    exclude:
      - '../../Service/{AbstractService.php}'
    public: true
