twig:
  form_themes:
    - '@CoreBundle/form/type/bootstrap.html.twig'
    - '@CoreBundle/form/type/form_tabs.html.twig'
    - '@CoreBundle/form/type/markdown.html.twig'
    - '@CoreBundle/form/type/super_collection.html.twig'